'use strict';
function event(text){s.events.unshift({t:s.runSeconds||0,text});s.events=s.events.slice(0,40)}
function storyOnce(id,text){const first=!s.storySeen[id];if(first){s.storySeen[id]=true;s.latestStory=text;event(text)}return first}
function visible(id){const p=s.prog;switch(id){
case'check_self':return true;case'listen':return p.checked_self;case'search_clearing':return p.listened;case'inspect_tracks':return p.searched_clearing;case'find_berries':return p.tracks;case'berries':return p.berry_patch;case'search_beyond':return p.stabilized;case'inspect_mushrooms':return p.beyond_clearing;case'mushrooms':return p.mushroom_patch;case'follow_fence':return p.mushroom_patch&&(s.res.mushrooms>0||(s.lifetime.mushrooms||0)>=2);case'approach_house':return p.fence_followed;case'inspect_door':return p.house_seen;case'enter_house':return p.door_checked;case'clear_debris':return p.house_inside;case'salvage_boards':case'pull_nails':case'gather_moss':case'chop':case'patch_frame':return p.debris_cleared;case'refasten':return p.frame_braced;case'seal_gaps':return p.boards_refastened;case'follow_path':return p.gaps_sealed;case'enter_deeper':return p.narrow_path;case'hear_movement':return p.deeper_forest;case'underbrush':return p.heard_movement;case'wolf_tracks':return p.underbrush_searched;case'thornbush':return p.wolf_tracks;case'dark_berries':return p.thorn_path;case'marker':return p.dark_berries_found;case'safer_route':return p.hunting_marker}return false}
function can(id){if(!visible(id))return false;const p=s.prog,r=s.res;switch(id){
case'check_self':return!p.checked_self;case'listen':return!p.listened;case'search_clearing':return!p.searched_clearing;case'inspect_tracks':return!p.tracks;case'find_berries':return!p.berry_patch;case'berries':return r.berries<cap();case'search_beyond':return!p.beyond_clearing;case'inspect_mushrooms':return!p.mushroom_patch;case'mushrooms':return r.mushrooms<cap();case'follow_fence':return!p.fence_followed;case'approach_house':return!p.house_seen;case'inspect_door':return!p.door_checked;case'enter_house':return!p.house_inside;case'clear_debris':return!p.debris_cleared;case'salvage_boards':return r.boards<cap();case'pull_nails':return r.nails<cap();case'gather_moss':return r.moss<cap();case'chop':return r.wood<cap();case'patch_frame':return!p.frame_braced&&r.wood>=2&&r.boards>=2;case'refasten':return!p.boards_refastened&&r.nails>=2;case'seal_gaps':return!p.gaps_sealed&&r.moss>=2;case'follow_path':return!p.narrow_path;case'enter_deeper':return!p.deeper_forest;case'hear_movement':return!p.heard_movement;case'underbrush':return!p.underbrush_searched;case'wolf_tracks':return!p.wolf_tracks;case'thornbush':return!p.thorn_path;case'dark_berries':return r.dark_berries<cap();case'marker':return!p.hunting_marker;case'safer_route':return!p.safe_route}return false}
function completedOneTime(id){if(ACTIONS[id].repeatable)return false;const p=s.prog;const map={check_self:'checked_self',listen:'listened',search_clearing:'searched_clearing',inspect_tracks:'tracks',find_berries:'berry_patch',search_beyond:'beyond_clearing',inspect_mushrooms:'mushroom_patch',follow_fence:'fence_followed',approach_house:'house_seen',inspect_door:'door_checked',enter_house:'house_inside',clear_debris:'debris_cleared',patch_frame:'frame_braced',refasten:'boards_refastened',seal_gaps:'gaps_sealed',follow_path:'narrow_path',enter_deeper:'deeper_forest',hear_movement:'heard_movement',underbrush:'underbrush_searched',wolf_tracks:'wolf_tracks',thornbush:'thorn_path',marker:'hunting_marker',safer_route:'safe_route'};return !!p[map[id]]}
function actionCycleXp(id){switch(id){case'check_self':case'listen':return 3;case'search_clearing':case'inspect_tracks':return 4;case'find_berries':case'inspect_mushrooms':case'hear_movement':return 5;case'berries':case'inspect_door':case'gather_moss':case'dark_berries':return 6;case'search_beyond':case'salvage_boards':case'pull_nails':case'underbrush':case'wolf_tracks':case'marker':return 7;case'follow_fence':case'approach_house':case'follow_path':case'mushrooms':return 8;case'chop':case'enter_deeper':return 9;case'enter_house':case'clear_debris':case'thornbush':case'safer_route':return 10;case'refasten':return 16;case'seal_gaps':return 18;case'patch_frame':return 20}return 1}
function liveXpRate(id){return actionCycleXp(id)/Math.max(.1,duration(id))}
function grantLiveActionXp(id,dt){if(!ACTIONS[id]||dt<=0)return;addXp(ACTIONS[id].skill,liveXpRate(id)*dt)}
function actionXpText(id){const a=ACTIONS[id],rate=liveXpRate(id),cycle=actionCycleXp(id);return`LIVE XP · ${a.skill} +${rate.toFixed(2)} Run/s / +${(rate*LOOP_XP_RATIO).toFixed(3)} Loop/s · ≈${cycle.toFixed(0)} Run per current cycle`}
function journeyReached(item){return !item.flag||!!s.prog[item.flag]}
function mycologyRisk(){return Math.max(.03,.28-level(s.runXp.Mycology)*.025-level(s.loopXp.Mycology)*.01)}
function toxicDamage(){return Math.max(.5,2.5-level(s.runXp.Mycology)*.15)}
function currentDecay(id){return DECAY_BASE*(1+(s.runSeconds||0)*.01)*(ACTIONS[id]?.strain??1)}
function complete(id){s.lifetime[id]=(s.lifetime[id]||0)+1;const p=s.prog,r=s.res;let first=false;switch(id){
case'check_self':p.checked_self=true;storyOnce(id,'Your clothes are damp and torn at one sleeve, but there is no serious wound. Your pockets are empty. Even the shape of your own hands feels strangely unfamiliar, as if your body remembers more than your mind does.');break;
case'listen':p.listened=true;storyOnce(id,'You force yourself to stay still. Wind moves high in the birches, a woodpecker knocks somewhere far off, and beneath it all you hear no road, no voices, no machinery—only forest.');break;
case'search_clearing':p.searched_clearing=true;storyOnce(id,'The ground around you is flattened in one place, but there is no bedroll, pack or campfire. A few broken twigs point toward the northern edge of the clearing, and the soil there has been disturbed recently.');break;
case'inspect_tracks':p.tracks=true;storyOnce(id,'The marks are too vague to be proper footprints. Some could be deer, but one narrow scrape looks almost like a boot heel dragged through wet needles. It disappears beneath a patch of brambles.');break;
case'find_berries':p.berry_patch=true;storyOnce(id,'Small blue berries hide beneath the leaves, with birds already picking at the ripest clusters. You recognize them without knowing how. That instinct is the first familiar thing you have felt since waking.');break;
case'berries':r.berries++;first=storyOnce(id,'You choose the darkest berries and leave the pale, damaged ones behind. The motion comes naturally: twist gently, do not crush the skin, keep the clean fruit separate from leaves and insects.');if(!first)event('You gather a portion of Wild Blueberries.');break;
case'search_beyond':p.beyond_clearing=true;storyOnce(id,'With food in you, the forest stops feeling like a wall. You move between the birches and notice old human signs: a cut branch, a stone shifted from a line, and bark scarred years ago by something sharper than an animal.');break;
case'inspect_mushrooms':p.mushroom_patch=true;storyOnce(id,'Orange caps crowd the moss beside a fallen birch. Most look familiar, but not all in exactly the same way. You realize that whatever knowledge remains in you is incomplete—and trusting it blindly could hurt you.');break;
case'mushrooms':first=storyOnce(id,'You slow down and inspect the folds beneath each cap, the stem, the color and the way it grows from the soil. Some differences are tiny. You begin building a new certainty from observation instead of memory.');if(Math.random()<mycologyRisk()){const d=toxicDamage();loseHp(d);event(`Toxic lookalike! You discard it after a wave of nausea. -${d.toFixed(1)} HP.`)}else{r.mushrooms++;if(!first)event('You identify and gather an edible Chanterelle.')}break;
case'follow_fence':p.fence_followed=true;storyOnce(id,'Beyond the mushroom patch you find a row of posts almost swallowed by moss. The wire is long gone, but the spacing is too regular to be natural. You follow it downhill, where the forest floor begins to show old cuts and buried stones.');break;
case'approach_house':p.house_seen=true;storyOnce(id,'A roofline appears between the trunks. The house is small, timber-framed and half-collapsed, with one side bowed outward and moss thick across the roof. It has been abandoned for years—but not erased. Someone once expected to come back here.');break;
case'inspect_door':p.door_checked=true;storyOnce(id,'The door hangs from one hinge. Around the latch are scratches too straight to be weathering, and several boards have been pried loose from inside. A square of cleaner wood shows where something used to be mounted beside the frame.');break;
case'enter_house':p.house_inside=true;storyOnce(id,'Inside, damp wood and old ash fill the air. A stone hearth still stands. One wall has collapsed inward, but the opposite corner remains dry. Broken furniture lies beneath the debris, and under it you glimpse iron nails, usable boards and signs of deliberate repairs from long ago.');break;
case'clear_debris':p.debris_cleared=true;storyOnce(id,'You drag rotten timber away from the surviving wall and sort what is useless from what can still serve. The work reveals old construction choices: boards overlapped against the wind, moss packed into gaps, and nails reused more than once.');break;
case'salvage_boards':r.boards++;first=storyOnce(id,'Most of the fallen boards crumble at the ends, but some still ring solid when you knock them. You trim your choices down to pieces that can take weight again instead of merely looking intact.');if(!first)event('You salvage one usable board.');break;
case'pull_nails':r.nails++;first=storyOnce(id,'The iron is old and bent, so pulling straight up would snap the wood around it. You work each nail loose a little at a time, saving metal that would be difficult to replace out here.');if(!first)event('You recover one reusable nail.');break;
case'gather_moss':r.moss++;first=storyOnce(id,'You remember the dry green-brown packing between the old wall boards. Nearby moss grows thick enough to gather in clean pads, soft now but dense enough to block wind once pressed into a narrow gap.');if(!first)event('You gather a bundle of clean packing moss.');break;
case'chop':r.wood++;first=storyOnce(id,'Young birch grows close to the ruin. You select straight poles no thicker than necessary; heavy timber would cost time and strength, while these can brace the weakened frame without wasting good wood.');if(!first)event('You cut one straight Young Birch Pole.');break;
case'patch_frame':r.wood-=2;r.boards-=2;p.frame_braced=true;storyOnce(id,'You lever the bowed frame closer to square and brace it with fresh birch before fitting salvaged boards across the weakest opening. The house is still a ruin, but the wall no longer looks ready to fall with the next hard wind.');break;
case'refasten':r.nails-=2;p.boards_refastened=true;storyOnce(id,'The recovered nails are ugly, but they bite. You straighten them against stone where you can and drive them through old holes at new angles, fastening the patched boards without splitting the dry timber.');break;
case'seal_gaps':r.moss-=2;p.gaps_sealed=true;storyOnce(id,'You twist and press moss into the worst seams until daylight disappears between the boards. The room is not warm yet, but the draft is weaker. For the first time, the ruin feels like somewhere you might survive a night.');break;
case'follow_path':p.narrow_path=true;storyOnce(id,'Behind the ruin, flattened grass and exposed roots form a narrow line between the trees. It is too faint to be a road, but too consistent to be random. You follow it beneath a canopy that grows darker with every step.');break;
case'enter_deeper':p.deeper_forest=true;storyOnce(id,'The birches give way to older trunks and thicker undergrowth. Damp earth muffles your steps. From here, the ruined house disappears completely after only a few turns.');break;
case'hear_movement':p.heard_movement=true;storyOnce(id,'A branch cracks ahead. Then leaves push aside in two heavy bursts and stop when you stop. Whatever is moving does not sound small, and it is close enough that you lower your breathing without thinking.');break;
case'underbrush':p.underbrush_searched=true;storyOnce(id,'Pressed leaves form a low channel through the brush. A tuft of grey-brown hair catches on a thorn, and the snapped stems are still wet inside. The trail is fresh.');break;
case'wolf_tracks':p.wolf_tracks=true;storyOnce(id,'In soft mud you find broad canine prints, deeper than the smaller tracks nearby. The pads point across your route rather than toward the house. For now, that feels like useful information rather than comfort.');break;
case'thornbush':p.thorn_path=true;storyOnce(id,'You work through the thorns sideways, protecting your face and hands. On the far side, the brush opens around a dark berry patch and a splintered wooden post almost hidden by ivy.');break;
case'dark_berries':r.dark_berries++;if(!p.dark_berries_found)p.dark_berries_found=true;first=storyOnce(id,'The berries are nearly black with a dull red bloom. You cannot match them to a safe memory, so you gather a small sample and leave eating them for later.');if(!first)event('You gather a sample of unfamiliar Dark Berries.');break;
case'marker':p.hunting_marker=true;storyOnce(id,'The broken post carries two shallow cuts and the remains of a carved arrow. Weather has softened the edges, but not enough to hide that a person made it. Someone once navigated this forest deliberately.');break;
case'safer_route':p.safe_route=true;storyOnce(id,'You circle wide around the muddy hollow and mark three reliable landmarks: a split pine, a pale boulder and the ruined fence line. The return to the house is longer, but safer—and repeatable.');break}
if(ACTIONS[id].repeatable&&(s.lifetime[id]||0)===AUTOMATION_UNLOCK)event(`${ACTIONS[id].name} automation unlocked.`);save()}
function start(id){if(!can(id))return false;s.active=id;s.progress=0;return true}
function stop(advance=true){s.active='';s.progress=0;if(advance)advanceQueueOrAuto()}
function queue(id){if(!visible(id))return;s.actionQueue.push(id);event(`${ACTIONS[id].name} added to Queue #${s.actionQueue.length}.`);if(!s.active)advanceQueueOrAuto();save()}
function clearQueue(){s.actionQueue=[];event('Action Queue cleared.');save()}
function skipQueueOrCurrent(){if(s.active){event(`${ACTIONS[s.active].name} skipped.`);s.active='';s.progress=0}else if(s.actionQueue.length){const id=s.actionQueue.shift();event(`${ACTIONS[id]?.name||id} removed from Queue.`)}advanceQueueOrAuto();save()}
function queueCount(id){return s.actionQueue.reduce((n,x)=>n+(x===id),0)}
function toggleAuto(id){if(!ACTIONS[id].repeatable||(s.lifetime[id]||0)<AUTOMATION_UNLOCK)return;s.autoActions[id]=!s.autoActions[id];if(s.autoActions[id]&&!s.active)advanceQueueOrAuto();save()}
function cyclePriority(id){if(!ACTIONS[id].repeatable)return;s.priorities[id]=(Number(s.priorities[id]??5)+1)%11;save()}
function advanceQueueOrAuto(){if(s.active)return;while(s.actionQueue.length){const q=s.actionQueue[0];if(!ACTIONS[q]||(completedOneTime(q)&&!ACTIONS[q].repeatable)){s.actionQueue.shift();continue}if(visible(q)&&can(q)){s.actionQueue.shift();start(q);return}return}let best='',bestP=-1;for(const id of ACTION_ORDER){if(!ACTIONS[id].repeatable||!s.autoActions[id]||(s.lifetime[id]||0)<AUTOMATION_UNLOCK||!can(id))continue;const p=Number(s.priorities[id]??5);if(p>bestP){bestP=p;best=id}}if(best)start(best)}
function consumeFood(id){const f=FOODS[id];if(!f||s.res[id]<=0)return;s.res[id]--;s.hp=Math.min(s.maxHp,s.hp+f.heal);s.foodTimers[id]=f.cooldown;s.foodsEaten[id]=(s.foodsEaten[id]||0)+1;addXp('Survival',f.survivalXp);event(`You eat ${f.name} and recover ${f.heal} HP.`);if(id==='berries'&&s.foodsEaten[id]>=6&&!s.prog.stabilized){s.prog.stabilized=true;storyOnce('stabilized','The shaking in your hands finally eases. Your stomach is not full, but the sharp edge of hunger is gone, and for the first time since waking you feel steady enough to leave the clearing.')}save()}
function processFoodTimers(dt){if(!s.autoEat)return;for(const [id,f] of Object.entries(FOODS)){if((s.res[id]||0)<=0)continue;let rem=Number(s.foodTimers[id]??f.cooldown);if(rem>0){rem=Math.max(0,rem-dt);s.foodTimers[id]=rem}if(rem>0)continue;const missing=s.maxHp-s.hp;if(missing+.001<f.heal)continue;consumeFood(id)}}
function die(){event('You collapse. This run ends, but one percent of every skill gain remains as Loop XP.');const loop={...s.loopXp},life={...s.lifetime},autos={...s.autoActions},priorities={...s.priorities},gen=s.generation+1,perm=s.perm,autoEat=s.autoEat;s=fresh();s.loopXp=loop;s.lifetime=life;s.autoActions=autos;s.priorities=priorities;s.generation=gen;s.perm=perm;s.autoEat=autoEat;recalcMax(false);s.hp=Math.min(s.maxHp,90);s.events.unshift({t:0,text:`Generation ${gen} begins. Loop XP and lifetime mastery remain.`});save()}
function hardReset(){s=fresh();recalcMax(false);event('TEST SAVE RESET · Generation 1 restarted from the beginning.');save()}
