'use strict';
function visible(id){const p=s.prog;switch(id){case'check_self':return true;case'listen':return p.checked_self;case'search_clearing':return p.listened;case'inspect_tracks':return p.searched_clearing;case'find_berries':return p.tracks;case'berries':return p.berry_patch;case'search_beyond':return p.stabilized;case'inspect_mushrooms':return p.beyond_clearing;case'mushrooms':return p.mushroom_patch;case'follow_fence':return p.mushroom_patch&&(s.res.mushrooms>0||(s.lifetime.mushrooms||0)>=2);case'approach_house':return p.fence_followed;case'inspect_door':return p.house_seen;case'enter_house':return p.door_checked;case'clear_debris':return p.house_inside;case'salvage_boards':case'pull_nails':case'gather_moss':case'chop':case'patch_frame':return p.debris_cleared;case'refasten':return p.frame_braced;case'seal_gaps':return p.boards_refastened}return false}
function can(id){if(!visible(id))return false;const p=s.prog,r=s.res;switch(id){case'check_self':return!p.checked_self;case'listen':return!p.listened;case'search_clearing':return!p.searched_clearing;case'inspect_tracks':return!p.tracks;case'find_berries':return!p.berry_patch;case'berries':return r.berries<cap();case'search_beyond':return!p.beyond_clearing;case'inspect_mushrooms':return!p.mushroom_patch;case'mushrooms':return r.mushrooms<cap();case'follow_fence':return!p.fence_followed;case'approach_house':return!p.house_seen;case'inspect_door':return!p.door_checked;case'enter_house':return!p.house_inside;case'clear_debris':return!p.debris_cleared;case'salvage_boards':return r.boards<cap();case'pull_nails':return r.nails<cap();case'gather_moss':return r.moss<cap();case'chop':return r.wood<cap();case'patch_frame':return!p.frame_braced&&r.wood>=2&&r.boards>=2;case'refasten':return!p.boards_refastened&&r.nails>=2;case'seal_gaps':return!p.gaps_sealed&&r.moss>=2}return false}
function completedOneTime(id){if(ACTIONS[id].repeatable)return false;const p=s.prog;switch(id){case'check_self':return p.checked_self;case'listen':return p.listened;case'search_clearing':return p.searched_clearing;case'inspect_tracks':return p.tracks;case'find_berries':return p.berry_patch;case'search_beyond':return p.beyond_clearing;case'inspect_mushrooms':return p.mushroom_patch;case'follow_fence':return p.fence_followed;case'approach_house':return p.house_seen;case'inspect_door':return p.door_checked;case'enter_house':return p.house_inside;case'clear_debris':return p.debris_cleared;case'patch_frame':return p.frame_braced;case'refasten':return p.boards_refastened;case'seal_gaps':return p.gaps_sealed}return false}
function actionXpText(id){const a=ACTIONS[id];let gain=0;switch(id){case'check_self':case'listen':gain=3;break;case'search_clearing':case'inspect_tracks':gain=4;break;case'find_berries':case'inspect_mushrooms':gain=5;break;case'berries':case'inspect_door':case'gather_moss':gain=6;break;case'search_beyond':case'salvage_boards':case'pull_nails':gain=7;break;case'follow_fence':case'approach_house':gain=8;break;case'chop':gain=9;break;case'enter_house':case'clear_debris':gain=10;break;case'refasten':gain=16;break;case'seal_gaps':gain=18;break;case'patch_frame':gain=20;break;case'mushrooms':return'XP / completion · edible: Mycology +8.00 Run / +0.08 Loop · toxic: +6.00 / +0.06'}return`XP / completion · ${a.skill} +${gain.toFixed(2)} Run / +${(gain*LOOP_XP_RATIO).toFixed(2)} Loop`}
function journeyReached(item){return !item.flag||!!s.prog[item.flag]}
function mycologyRisk(){return Math.max(.03,.28-level(s.runXp.Mycology)*.025-level(s.loopXp.Mycology)*.01)}
function toxicDamage(){return Math.max(.5,2.5-level(s.runXp.Mycology)*.15)}
function complete(id){s.lifetime[id]=(s.lifetime[id]||0)+1;const p=s.prog,r=s.res;let first=false;switch(id){
case'check_self':p.checked_self=true;addXp('Survival',3);storyOnce(id,'Your clothes are damp and torn at one sleeve, but there is no serious wound. Your pockets are empty. Even the shape of your own hands feels strangely unfamiliar, as if your body remembers more than your mind does.');break;
case'listen':p.listened=true;addXp('Survival',3);storyOnce(id,'You force yourself to stay still. Wind moves high in the birches, a woodpecker knocks somewhere far off, and beneath it all you hear no road, no voices, no machinery—only forest.');break;
case'search_clearing':p.searched_clearing=true;addXp('Survival',4);storyOnce(id,'The ground around you is flattened in one place, but there is no bedroll, pack or campfire. A few broken twigs point toward the northern edge of the clearing, and the soil there has been disturbed recently.');break;
case'inspect_tracks':p.tracks=true;addXp('Survival',4);storyOnce(id,'The marks are too vague to be proper footprints. Some could be deer, but one narrow scrape looks almost like a boot heel dragged through wet needles. It disappears beneath a patch of brambles.');break;
case'find_berries':p.berry_patch=true;addXp('Survival',5);storyOnce(id,'Small blue berries hide beneath the leaves, with birds already picking at the ripest clusters. You recognize them without knowing how. That instinct is the first familiar thing you have felt since waking.');break;
case'berries':r.berries++;addXp('Foraging',6);first=storyOnce(id,'You choose the darkest berries and leave the pale, damaged ones behind. The motion comes naturally: twist gently, do not crush the skin, keep the clean fruit separate from leaves and insects.');if(!first)event('You gather a portion of Wild Blueberries.');break;
case'search_beyond':p.beyond_clearing=true;addXp('Survival',7);storyOnce(id,'With food in you, the forest stops feeling like a wall. You move between the birches and notice old human signs: a cut branch, a stone shifted from a line, and bark scarred years ago by something sharper than an animal.');break;
case'inspect_mushrooms':p.mushroom_patch=true;addXp('Mycology',5);storyOnce(id,'Orange caps crowd the moss beside a fallen birch. Most look familiar, but not all in exactly the same way. You realize that whatever knowledge remains in you is incomplete—and trusting it blindly could hurt you.');break;
case'mushrooms':first=storyOnce(id,'You slow down and inspect the folds beneath each cap, the stem, the color and the way it grows from the soil. Some differences are tiny. You begin building a new certainty from observation instead of memory.');if(Math.random()<mycologyRisk()){const d=toxicDamage();loseHp(d);addXp('Mycology',6);event(`Toxic lookalike! You discard it after a wave of nausea. -${d.toFixed(1)} HP.`)}else{r.mushrooms++;addXp('Mycology',8);if(!first)event('You identify and gather an edible Chanterelle.')}break;
case'follow_fence':p.fence_followed=true;addXp('Survival',8);storyOnce(id,'Beyond the mushroom patch you find a row of posts almost swallowed by moss. The wire is long gone, but the spacing is too regular to be natural. You follow it downhill, where the forest floor begins to show old cuts and buried stones.');break;
case'approach_house':p.house_seen=true;addXp('Survival',8);storyOnce(id,'A roofline appears between the trunks. The house is small, timber-framed and half-collapsed, with one side bowed outward and moss thick across the roof. It has been abandoned for years—but not erased. Someone once expected to come back here.');break;
case'inspect_door':p.door_checked=true;addXp('Survival',6);storyOnce(id,'The door hangs from one hinge. Around the latch are scratches too straight to be weathering, and several boards have been pried loose from inside. A square of cleaner wood shows where something used to be mounted beside the frame.');break;
case'enter_house':p.house_inside=true;addXp('Survival',10);storyOnce(id,'Inside, damp wood and old ash fill the air. A stone hearth still stands. One wall has collapsed inward, but the opposite corner remains dry. Broken furniture lies beneath the debris, and under it you glimpse iron nails, usable boards and signs of deliberate repairs from long ago.');break;
case'clear_debris':p.debris_cleared=true;addXp('Crafting',10);storyOnce(id,'You drag rotten timber away from the surviving wall and sort what is useless from what can still serve. The work reveals old construction choices: boards overlapped against the wind, moss packed into gaps, and nails reused more than once.');break;
case'salvage_boards':r.boards++;addXp('Crafting',7);first=storyOnce(id,'Most of the fallen boards crumble at the ends, but some still ring solid when you knock them. You trim your choices down to pieces that can take weight again instead of merely looking intact.');if(!first)event('You salvage one usable board.');break;
case'pull_nails':r.nails++;addXp('Crafting',7);first=storyOnce(id,'The iron is old and bent, so pulling straight up would snap the wood around it. You work each nail loose a little at a time, saving metal that would be difficult to replace out here.');if(!first)event('You recover one reusable nail.');break;
case'gather_moss':r.moss++;addXp('Foraging',6);first=storyOnce(id,'You remember the dry green-brown packing between the old wall boards. Nearby moss grows thick enough to gather in clean pads, soft now but dense enough to block wind once pressed into a narrow gap.');if(!first)event('You gather a bundle of clean packing moss.');break;
case'chop':r.wood++;addXp('Woodcutting',9);first=storyOnce(id,'Young birch grows close to the ruin. You select straight poles no thicker than necessary; heavy timber would cost time and strength, while these can brace the weakened frame without wasting good wood.');if(!first)event('You cut one straight Young Birch Pole.');break;
case'patch_frame':r.wood-=2;r.boards-=2;p.frame_braced=true;addXp('Crafting',20);storyOnce(id,'You lever the bowed frame closer to square and brace it with fresh birch before fitting salvaged boards across the weakest opening. The house is still a ruin, but the wall no longer looks ready to fall with the next hard wind.');break;
case'refasten':r.nails-=2;p.boards_refastened=true;addXp('Crafting',16);storyOnce(id,'The recovered nails are ugly, but they bite. You straighten them against stone where you can and drive them through old holes at new angles, fastening the patched boards without splitting the dry timber.');break;
case'seal_gaps':r.moss-=2;p.gaps_sealed=true;addXp('Crafting',18);storyOnce(id,'You twist and press moss into the worst seams until daylight disappears between the boards. The room is not warm yet, but the draft is weaker. For the first time, the ruin feels like somewhere you might survive a night.');break}
if(ACTIONS[id].repeatable&&(s.lifetime[id]||0)===AUTOMATION_UNLOCK)event(`${ACTIONS[id].name} automation unlocked.`);save()}
function start(id){if(!can(id))return;s.active=id;s.progress=0;render()}
function stop(advance=true){s.active='';s.progress=0;if(advance)advanceQueueOrAuto();render()}
function queue(id){if(!visible(id))return;s.nextAction=id;event(`${ACTIONS[id].name} queued. It will run until its natural stop condition.`);if(!s.active)advanceQueueOrAuto();save();render()}
function toggleAuto(id){if(!ACTIONS[id].repeatable||(s.lifetime[id]||0)<AUTOMATION_UNLOCK)return;s.autoActions[id]=!s.autoActions[id];if(s.autoActions[id]&&!s.active)advanceQueueOrAuto();save();render()}
function cyclePriority(id){if(!ACTIONS[id].repeatable)return;s.priorities[id]=(Number(s.priorities[id]??5)+1)%11;save();render()}
function advanceQueueOrAuto(){if(s.active)return;if(s.nextAction){const q=s.nextAction;s.nextAction='';if(can(q)){start(q);return}}let best='',bestP=-1;for(const id of ACTION_ORDER){if(!ACTIONS[id].repeatable||!s.autoActions[id]||(s.lifetime[id]||0)<AUTOMATION_UNLOCK||!can(id))continue;const p=Number(s.priorities[id]??5);if(p>bestP){bestP=p;best=id}}if(best)start(best)}
function consumeFood(id){const f=FOODS[id];if(!f||s.res[id]<=0)return;s.res[id]--;s.hp=Math.min(s.maxHp,s.hp+f.heal);s.foodTimers[id]=f.cooldown;s.foodsEaten[id]=(s.foodsEaten[id]||0)+1;addXp('Survival',f.survivalXp);event(`You eat ${f.name} and recover ${f.heal} HP.`);if(id==='berries'&&s.foodsEaten[id]>=6&&!s.prog.stabilized){s.prog.stabilized=true;storyOnce('stabilized','The shaking in your hands finally eases. Your stomach is not full, but the sharp edge of hunger is gone, and for the first time since waking you feel steady enough to leave the clearing.')}save()}
function processFoodTimers(dt){if(!s.autoEat)return;for(const [id,f] of Object.entries(FOODS)){if((s.res[id]||0)<=0)continue;let rem=Number(s.foodTimers[id]??f.cooldown);if(rem>0){rem=Math.max(0,rem-dt);s.foodTimers[id]=rem}if(rem>0)continue;const missing=s.maxHp-s.hp;if(missing+.001<f.heal)continue;consumeFood(id)}}
function die(){const loop={...s.loopXp},life={...s.lifetime},autos={...s.autoActions},priorities={...s.priorities},gen=s.generation+1,perm=s.perm,autoEat=s.autoEat;s=fresh();s.loopXp=loop;s.lifetime=life;s.autoActions=autos;s.priorities=priorities;s.generation=gen;s.perm=perm;s.autoEat=autoEat;recalcMax(false);s.hp=Math.min(s.maxHp,90);s.events.unshift({t:0,text:`Generation ${gen} begins. Loop XP and lifetime mastery remain.`});save();render()}
