'use strict';
const actionWrap=document.getElementById('actions');
for(const id of ACTION_ORDER){
  const a=ACTIONS[id],card=document.createElement('div');card.className='action';card.id='card_'+id;
  card.innerHTML=`<div class="actionRow"><button class="actionExpand"><span class="actionName"></span><span class="time"></span></button><button class="mini runBtn">RUN</button><button class="mini queueBtn">QUEUE</button><button class="mini autoBtn">AUTO</button><button class="mini priorityBtn">P5</button></div><div class="actionProgress"><i></i></div><div class="actionBody"><div class="meta"></div><div class="mastery"></div></div>`;
  actionWrap.appendChild(card);
  const body=card.querySelector('.actionBody');card.querySelector('.actionExpand').onclick=()=>body.classList.toggle('open');
  card.querySelector('.runBtn').onclick=()=>s.active===id?stop(false):start(id,false);
  card.querySelector('.queueBtn').onclick=()=>queue(id);
  card.querySelector('.autoBtn').onclick=()=>toggleAuto(id);
  card.querySelector('.priorityBtn').onclick=()=>cyclePriority(id);
}
document.getElementById('autoEatBtn').onclick=()=>{s.autoEat=!s.autoEat;event(`Auto-Eat ${s.autoEat?'enabled':'disabled'}. Food timers ${s.autoEat?'resume':'freeze'}.`);save();render()};
let last=performance.now();
function tick(now){const dt=Math.min((now-last)/1000,.25);last=now;
  if(s.active){const id=s.active;if(!can(id)){stop(true)}else{s.runSeconds+=dt;loseVitality(currentDecay(id)*dt);s.progress+=dt;if(s.vitality<=0){s.vitality=0;render();die()}else if(s.progress>=duration(id)){s.progress-=duration(id);complete(id);if(s.activeOnce||!can(id))stop(true)}}}
  processFoodTimers(dt);if(!s.active)advanceQueueOrAuto();render();requestAnimationFrame(tick)
}
function foodTimerText(id){const f=FOODS[id],rem=Number(s.foodTimers[id]??f.cooldown),amount=Number(s.res[id]||0);if(!s.autoEat)return`PAUSED ${rem.toFixed(1)}s`;if(amount<=0)return`FROZEN ${rem.toFixed(1)}s`;if(rem<=.01)return'READY';return rem.toFixed(1)+'s'}
function render(){
  document.getElementById('vitText').textContent=`VITALITY ${Math.max(0,Math.floor(s.vitality))} / ${Math.floor(s.maxVitality)}`;document.getElementById('vitFill').style.width=(100*Math.max(0,s.vitality)/s.maxVitality)+'%';document.getElementById('genText').textContent='GEN '+s.generation;document.getElementById('runText').textContent='RUN '+fmt(s.runSeconds);document.getElementById('eatText').textContent='AUTO-EAT '+(s.autoEat?'ON':'OFF');document.getElementById('permText').textContent='POINTS '+s.perm;document.getElementById('permInside').textContent=s.perm;document.getElementById('autoEatBtn').textContent='Auto-Eat '+(s.autoEat?'ON':'OFF');
  document.getElementById('activeText').textContent=s.active?`RUNNING · ${currentDecay(s.active).toFixed(2)} VIT/s`:'IDLE · no Vitality loss';document.getElementById('queueText').textContent='NEXT ACTION (ONCE): '+(s.nextAction?ACTIONS[s.nextAction].name:'none');
  document.getElementById('story').textContent=s.prog.trail?'The trail is open. Claws scrape against stone somewhere between the trees. The combat zone begins beyond this point.':s.prog.knife?'The Stone Knife changes what is possible. The Dark Forest can now be reached if you cut a path through the thorns.':s.prog.shelter?'The lean-to is finished. Granite and strong nettle fibers are now within reach.':'You wake in a cold clearing beneath a sky you almost remember. Blueberries and Chanterelles grow beneath wet birch leaves, and the forest stands silent around you.';
  const steps=[['Build a Lean-to Shelter',s.prog.shelter],['Find Granite Stone',s.res.stone>0||s.prog.knife],['Craft a Stone Knife',s.prog.knife],['Open the Dark Forest Trail',s.prog.trail]];let found=false;document.getElementById('journey').innerHTML=steps.map((x,i)=>{const done=!!x[1],mark=done?'✓':(!found?'▶':'·');if(!done)found=true;return`<div class="${done?'done':''}">${mark} ${i+1}. ${x[0]}</div>`}).join('');
  document.getElementById('resources').innerHTML=RESOURCE_ORDER.map(k=>{if(FOODS[k]){const f=FOODS[k],rate=f.heal/f.cooldown;return`<div class="resource foodrow"><span>${RESOURCE_NAMES[k]}</span><b>${s.res[k]} / ${cap()} · ⏱ ${foodTimerText(k)}<br><small>+${f.heal} VIT · ${rate.toFixed(1)}/s</small></b></div>`}return`<div class="resource"><span>${RESOURCE_NAMES[k]}</span><b>${s.res[k]} / ${cap()}</b></div>`}).join('');
  document.getElementById('skills').innerHTML=SKILLS.map(sk=>{const rl=sk==='Endurance'?enduranceLevel(s.runXp[sk]):level(s.runXp[sk]),ll=sk==='Endurance'?enduranceLevel(s.loopXp[sk]):level(s.loopXp[sk]);return`<div class="skillrow"><span class="skillname">${sk}</span><span class="skillxp">Run Lv.${rl} · ${Math.floor(s.runXp[sk])} XP<br>Loop Lv.${ll} · ${Math.floor(s.loopXp[sk])} XP${sk==='Endurance'?` · Max Vitality +${rl+ll*2}`:''}</span></div>`}).join('');
  for(const id of ACTION_ORDER){const a=ACTIONS[id],d=document.getElementById('card_'+id),active=s.active===id,life=s.lifetime[id]||0,autoUnlocked=life>=AUTOMATION_UNLOCK,autoOn=!!s.autoActions[id],priority=Number(s.priorities[id]??5);d.querySelector('.actionName').textContent=a.name;d.querySelector('.time').textContent=duration(id).toFixed(1)+'s'+(active?' ▶':'');d.querySelector('.meta').textContent=(unlocked(id)?a.desc:'🔒 Not unlocked yet')+` · ${a.skill} Run Lv.${level(s.runXp[a.skill])} / Loop Lv.${level(s.loopXp[a.skill])}`;const rb=d.querySelector('.runBtn');rb.textContent=active?'STOP':'RUN';rb.disabled=!active&&!can(id);const qb=d.querySelector('.queueBtn');qb.disabled=!unlocked(id);qb.textContent=s.nextAction===id?'QUEUED':'QUEUE';const ab=d.querySelector('.autoBtn');ab.disabled=!autoUnlocked;ab.textContent=autoUnlocked?(autoOn?'AUTO✓':'AUTO'):'AUTO🔒';d.querySelector('.priorityBtn').textContent='P'+priority;const decay=(DECAY_BASE+DECAY_PER_ACTIVE_MINUTE*(s.runSeconds/60))*a.strain;d.querySelector('.mastery').textContent=(autoUnlocked?`Lifetime ${life} · Auto unlocked`:`Lifetime ${life} / ${AUTOMATION_UNLOCK} to unlock Auto`)+` · Priority ${priority}/10 · Strain ${a.strain.toFixed(2)}× · Decay now ${decay.toFixed(2)} VIT/s`;d.querySelector('.actionProgress i').style.width=active?Math.min(100,100*s.progress/duration(id))+'%':'0%'}
  document.getElementById('events').innerHTML=s.events.map(e=>`<div>${fmt(e.t)} &nbsp; ${e.text}</div>`).join('');
}
render();setInterval(save,3000);requestAnimationFrame(tick);
